### ISSUE TITLE
KCauldron - Stats lost on world change

### ISSUE THREAD

**Issue by Jerry996666** [Mixac1/DangerRPG#12]
Hi I'm loving the mod and wanted to use it in my KCauldron server, latest update, however whenever you switch worlds (Done via multiverse plugin) your stats completely reset as if you didn't gain or use any. Not sure if there is anything you could do, but I figured I'd post it as an issue. Thank you for the awesome mod!

**Comment by Mixac1** [comment]
Ok, I will test it.

**Comment by Mixac1** [comment]
Does this begin to occur in the new update?

**Comment by Jerry996666** [comment]
No I just started testing your mod yesterday as that's when I found it haha. I am testing in a server with ForgeEssentials with it's multi dimensional world system to see if it does it as well. I will report back any if it works there or not. If it does, I'm going to be dropping KCauldron and going pure Forge server then.

**Comment by Jerry996666** [comment]
Stats and such carry over when using a pure Forge server with Forge Essentials adding in worlds a dims over what bukkit did with Multiverse.
