### ISSUE TITLE
Suggestion - Max player level config

### ISSUE THREAD

**Issue by KryptonCaptain** [Mixac1/DangerRPG#14]
Currently, you can set the max level for tools/items with
    # Set max level of RPG items
    I:maxLevel=100

It would be nice to have a similar option to set the max level for player attributes (default currently 1000) - aside from those attributes that already have a cap (20)

This could also benefit servers, that want to cap player level, but then increase cap on updates, like WOW does.

**Comment by Mixac1** [comment]
Configure of player stats will be added in next update. But changing of some stats (mobs speed, jump height, etc) can be dangerous, because their values don't have linear dependence.

**Comment by Mixac1** [comment]
Realized
