### ISSUE TITLE
1.0.7 - Entities not spawning at full health

### ISSUE THREAD

**Issue by KryptonCaptain** [Mixac1/DangerRPG#16]
Went to confirm #15, and spawned in near a fortress. Blazes spawned from the spawner had level data, but were not at the adjusted max health on spawn 

![2016-09-28_22 23 17](https://cloud.githubusercontent.com/assets/8790829/18913334/a1f7f8f8-85ca-11e6-92b5-a226947935e0.png)

Minor report - didn't need a new issue for this:
Your build file didn't correctly replace the $(version) annotations in your code with the version number of the build. Can be seen in the config and mcmod.info file.

**Comment by Mixac1** [comment]
I have fixed build file, but I don't understand why blazes spawn without full health.
I check it in last update, but I didn't find bug.
![](http://image.prntscr.com/image/2ea1873768484eb3b77dc050cd71ece0.png)

**Comment by KryptonCaptain** [comment]
Was being caused by EnderZoo. Specifically, this section of the config.
```
    # When enabled health and base damage for all non Ender Zoo mobs will be modified based on difficulty [default: true]
    B:globalDifficultyModifierEnabled=true

    # When in easy difficulty base attack damage is multiplied by this value
    D:globalEasyAttackModifier=0.9

    # When in easy difficulty base health is multiplied by this value, rounded to the nearest whole 'heart'
    D:globalEasyHealthModifier=1.0

    # When in easy difficulty base attack damage is multiplied by this value
    D:globalHardAttackModifier=1.1

    # When in hard mode base health is multiplied by this value, rounded to the nearest whole 'heart'
    D:globalHardHealthModifier=1.0

    # When in easy difficulty base attack damage is multiplied by this value
    D:globalNormalAttackModifier=1.0

    # When in normal difficultry base health is multiplied by this value, rounded to the nearest whole 'heart'
    D:globalNormalHealthModifier=1.0
```
When game was set to Easy or Hard difficulty, it was altering the base health of the mobs. Resolved by changing this to false
```
    # When enabled health and base damage for all non Ender Zoo mobs will be modified based on difficulty [default: true]
    B:globalDifficultyModifierEnabled=false
```

Closing issue, as it was not your fault :)
Useful note for future reference if someone else has this issue.
