### ISSUE TITLE
Items lose enchantments when they level up

### ISSUE THREAD

**Issue by platinumphoenix2** [Mixac1/DangerRPG#18]
If an item has enchantment(s) and it levels up, it will lose all of the enchantments.

(Not sure if this was intentional).

**Comment by Mixac1** [comment]
Oh, it is a very interesting

**Comment by Mixac1** [comment]
I have just tried fix it. 
Could you check it in new version?

**Comment by platinumphoenix2** [comment]
Sure thing, is it the same file (1.0.8) or it still not uploaded yet?

**Comment by platinumphoenix2** [comment]
Issue fixed.
