### ISSUE TITLE
Strength Stat only working on Swords and tools

### ISSUE THREAD

**Issue by platinumphoenix2** [Mixac1/DangerRPG#19]
I'm not sure if that was intentional, but the strength stat only works on swords and tools.
Is it supposed to work with a bare hand or other items? (Otherwise, it seems like just an enchantment).
If so, it doesn't apply them.

**Comment by Mixac1** [comment]
It is work only on items with stat 'Strenght Multiplier'

**Comment by platinumphoenix2** [comment]
Okay, thanks for clarifying.
