### ISSUE TITLE
Workbench Server Crash

### ISSUE THREAD

**Issue by xeloxxleox** [Mixac1/DangerRPG#2]
The crash happens when I click the workbench to start crafting.

4:32:50 PM [Server thread/ERROR]: Encountered an unexpected exception
4:32:50 PM java.lang.NoClassDefFoundError: mixac1/dangerrpg/client/gui/GuiRPGWorkbench
4:32:50 PM 	at mixac1.dangerrpg.inventory.ContainerRPGWorkbench.<init>(ContainerRPGWorkbench.java:38) ~[ContainerRPGWorkbench.class:?]
4:32:50 PM 	at mixac1.dangerrpg.init.RPGGuiHandlers.getServerGuiElement(RPGGuiHandlers.java:38) ~[RPGGuiHandlers.class:?]
4:32:51 PM 	at cpw.mods.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:243) ~[NetworkRegistry.class:?]
4:32:51 PM 	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:75) ~[FMLNetworkHandler.class:?]
4:32:51 PM 	at net.minecraft.entity.player.EntityPlayer.openGui(Unknown Source) ~[yz.class:?]
4:32:51 PM 	at mixac1.dangerrpg.block.BlockRPGWorkbench.func_149727_a(BlockRPGWorkbench.java:54) ~[BlockRPGWorkbench.class:?]
4:32:51 PM 	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source) ~[mx.class:?]
4:32:51 PM 	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
4:32:51 PM 	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
4:32:51 PM 	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
4:32:51 PM 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
4:32:51 PM 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
4:32:51 PM 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
4:32:51 PM 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
4:32:51 PM 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
4:32:51 PM 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
4:32:51 PM 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
4:32:51 PM Caused by: java.lang.ClassNotFoundException: mixac1.dangerrpg.client.gui.GuiRPGWorkbench
4:32:51 PM 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
4:32:51 PM 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
4:32:51 PM 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
4:32:51 PM 	... 17 more
4:32:51 PM Caused by: java.lang.RuntimeException: Attempted to load class mixac1/dangerrpg/client/gui/GuiRPGWorkbench for invalid side SERVER
4:32:51 PM 	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
4:32:51 PM 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
4:32:51 PM 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
4:32:51 PM 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
4:32:51 PM 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
4:32:51 PM 	... 17 more
4:32:51 PM [Server thread/ERROR]: This crash report has been saved to: C:\Users\alin\Desktop\SERVER MC\1.7.10 X\.\crash-reports\crash-2016-09-15_16.32.50-server.txt
4:32:51 PM [INFO] Stopping server
4:32:52 PM [INFO] Saving players
4:32:52 PM [INFO] Saving worlds
4:32:52 PM [INFO] Saving chunks for level 'world'/Overworld
4:32:52 PM [INFO] Saving chunks for level 'world'/Nether
4:32:52 PM [INFO] Saving chunks for level 'world'/The End
4:32:52 PM [INFO] Saving chunks for level 'world'/Betweenlands
4:32:52 PM [INFO] Saving chunks for level 'world'/Twilight Forest
4:32:52 PM [INFO] Saving chunks for level 'world'/Atum
4:32:52 PM [INFO] Saving chunks for level 'world'/Underdark
4:32:52 PM [INFO] Saving chunks for level 'world'/The Last Millenium
4:32:52 PM [INFO] [FML]: Unloading dimension 0
4:32:52 PM [INFO] [FML]: Unloading dimension -1
4:32:52 PM [INFO] [FML]: Unloading dimension 1
4:32:52 PM [INFO] [FML]: Unloading dimension 20
4:32:52 PM [INFO] [FML]: Unloading dimension 7
4:32:52 PM [INFO] [FML]: Unloading dimension 17
4:32:52 PM [INFO] [FML]: Unloading dimension -100
4:32:52 PM [INFO] [FML]: Unloading dimension -112
4:32:52 PM [INFO] [FML]: Applying holder lookups
4:32:52 PM [INFO] [FML]: Holder lookups applied
4:32:52 PM [INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
4:32:52 PM Picked up _JAVA_OPTIONS: -Xmx3G
[GUI] The server has stopped...

**Comment by Mixac1** [comment]
Thanks. This is my big fail.
Fixed. Wait new version.
