### ISSUE TITLE
Knives and Tomahawks bug

### ISSUE THREAD

**Issue by platinumphoenix2** [Mixac1/DangerRPG#20]
After attacking an entity once with a knife or tomahawk of any type (stone, iron, gold, etc), you won't be able to attack again, even if you switch to another tool or sword.

- You can still attack with items that do not level up, such as blocks, food, and tools/swords from other mods.

**Comment by Mixac1** [comment]
Is this happen after melee attack or range?

**Comment by platinumphoenix2** [comment]
After a Melee attack.

**Comment by Mixac1** [comment]
I found this bug in all RPGable items.
I have just fixed it.

**Comment by Mixac1** [comment]
Is the bug appear?

**Comment by platinumphoenix2** [comment]
Bug is fixed.
However, when hitting (with an RPGable tool) on anything but an entity (like in the air or on a block), the animation of the sword swinging doesn't appear.

- This is bad when mining as the Pickaxe doesn't have it's animation when hitting a block.

Version: 1.1.1

**Comment by Mixac1** [comment]
Could you contact with me in curse private chat or skype?

**Comment by platinumphoenix2** [comment]
Ok, I've messaged you on Curse.
