### ISSUE TITLE
crash when he attacks 

### ISSUE THREAD

**Issue by ASirJoker** [Mixac1/DangerRPG#21]
Cant do any damage with melee weapons and crash when he uses his fist  

9:47:09 PM CONSOLE: thread/ERROR] [FML]: Exception caught during firing event mixac1.dangerrpg.api.event.DealtDamageEvent@14489246:
9:47:10 PM CONSOLE: thread/ERROR] [FML]: Index: 1 Listeners:
9:47:10 PM CONSOLE: thread/ERROR] [FML]: 0: NORMAL
9:47:10 PM CONSOLE: thread/ERROR] [FML]: 1: ASM: mixac1.dangerrpg.event.EventHandlerItem@4cb80a8e onDealtDamage(Lmixac1/dangerrpg/api/event/DealtDamageEvent;)V

**Comment by Mixac1** [comment]
Duplicate isuue [#17](https://github.com/Mixac1/DangerRPG/issues/17)
