### ISSUE TITLE
Issue with sword swinging animations [1.1.2]

### ISSUE THREAD

**Issue by platinumphoenix2** [Mixac1/DangerRPG#23]
After attacking an entity with an RPG item (like knives), the animation randomly glitches and begins to glitch other RPGable items (like Diamond pickaxe).

**Comment by Mixac1** [comment]
I've just fixed it.

**Comment by platinumphoenix2** [comment]
In 1.1.2 or a new version? 
In 1.1.2 it still happens.

**Comment by Mixac1** [comment]
Ofc, in new version :)
