### ISSUE TITLE
the indicator of hunger + animation

### ISSUE THREAD

**Issue by SvEgiiVEteR** [Mixac1/DangerRPG#25]
possible option to return to the place?
use mods:
HungerOverhaul-1.7.10-1.0.0.jenkins86.jar
AppleCore-mc1.7.10-1.3.2.jar
SpiceOfLife-mc1.7.10-1.3.6.jar
and I would like to see the indicator satiety

and notice that all the tools will go missing, sometimes the animation of the left mouse button on the block and the air.

**Comment by Mixac1** [comment]
Satiety indicator becomes visible when player is hunger.

Could you send me screenshot?

**Comment by SvEgiiVEteR** [comment]
I'm talking about is the yellow highlighted position in the indicator of food.
http://i.imgur.com/9ianTOfl.jpg
http://i.imgur.com/fykgFdQl.jpg
you don't have one))

**Comment by Mixac1** [comment]
Ok, I will try add option in config for enable default satiety indicator.
Also, if you want, you can write in Russian language. I'm russian developer.

**Comment by SvEgiiVEteR** [comment]
аа ок)))тогда ещё хотел узнать клавиши С и F  их где использовать?

**Comment by Mixac1** [comment]
F нигде пока. Я ее, наверное, забыл выключить. С - для броска метательных оружий (нож и томагавк).
Анимацию я починил уже. Будет в следующей обнове.

**Comment by SvEgiiVEteR** [comment]
@Mixac1 кстати не нашёл у вас опции что бы сделать по умолчанию иконку персонажа без персонажа
чисто текст,статы и бары нужны
а то переключать O надоедает постоянно)

**Comment by Mixac1** [comment]
Ищи в ClientConfig - guiDafaultHUDMode.

**Comment by SvEgiiVEteR** [comment]
нет это не то(
когда я ставлю 
simple digital
то появляеться тока имя персонажа и все.. нет ни баров ни цифр
тока имя.
не то когда нажимаешь O

**Comment by Mixac1** [comment]
Странно. Я проверю это

**Comment by SvEgiiVEteR** [comment]
вот так это выглядит
http://i.imgur.com/NdFL0qI.png
клавиша O чинит

**Comment by Mixac1** [comment]
Добавил опцию для включения стандартной полоски сытости в конфиг файл. Жди следующего обновления.

**Comment by SvEgiiVEteR** [comment]
спасибо всё есть, анимация тоже пока робит)
