### ISSUE TITLE
Staff items error

### ISSUE THREAD

**Issue by Azalthar** [Mixac1/DangerRPG#27]
Hi,

First, thank you for your awesome mod ! It is exactly what i was looking for.
I encounter an issue when I tried to see the "Item Info" of any "Power Staff" and "Staff". It shut down the internal server and I have to restart Minecraft from the launcher.

**Comment by Mixac1** [comment]
Oh, thank you. It is issue #26, but you helped me find this bug.
I've just fixed it. Wait for the next update.
