### ISSUE TITLE
Item levelling

### ISSUE THREAD

**Issue by KryptonCaptain** [Mixac1/DangerRPG#3]
How are bows supposed to be levelled? As they do not increase from attacks using bow item (not firing), or from hits with arrows.

Also, because the vanilla swords are not added to list of items that can level, they gain infinite attack speed

I do not think that items should gain more enchantability as they level up though, and perhaps there could be a config to change how much durability a tool gains when it levels up.

**Comment by Mixac1** [comment]
Experience must increases from arrow and melee atack too. I have just fixed this bug.

I have hust fixed infinite attack speed in not levelable items.

Setting of all levelable items and entity stats will be added in future.

Thanks for you report!
