### ISSUE TITLE
Recipe issues

### ISSUE THREAD

**Issue by KryptonCaptain** [Mixac1/DangerRPG#5]
There are two recipes for compressed bedrock at the moment. Is this intended, or bug?
![drpg_recip2](https://cloud.githubusercontent.com/assets/8790829/18607715/85d432f0-7d18-11e6-9ca2-048dc9c90af2.PNG)
![drpg_recip1](https://cloud.githubusercontent.com/assets/8790829/18607716/8969526a-7d18-11e6-9ced-c3da21cbfdd8.PNG)

Dark Matter also does not have a recipe - or is there special way to create it?

**Comment by Mixac1** [comment]
It is bug. Fixed.
