### ISSUE TITLE
Lost status in a strange way

### ISSUE THREAD

**Issue by xeloxxleox** [Mixac1/DangerRPG#7]
When you have points in stats and you die, you lost all the bonuses you had like from 26 hp back to 20 but the problem is that the points are still there.

**Comment by Mixac1** [comment]
This is feature. When player die, he will lose 3 random level stats. You can setting it in config. "Player Category" -> playerLoseLvlCount

**Comment by xeloxxleox** [comment]
No no no you don't get it. I know know you lose stats bu the problem is that when you lose satts like from 2 to 0 points in health the points are still there even if you have no bonuses in health.

**Comment by Mixac1** [comment]
Oh, really

**Comment by Mixac1** [comment]
Fixed
